language: android
android:
  components:
  - tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - android-25
  - platform-tools

before_install:
- chmod +x .buildscript/deploy_snapshot.sh
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: "./gradlew build --stacktrace"
after_success:
- ".buildscript/deploy_snapshot.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: Mr706hWcXZoE2V2Om88dEuZJySFdPoTUNKJNtbcXP2s4brOQ4kE5pnAifmeFjehaBpQUOTziC3OASCV58gQZYBvSk3Ewl0ALeCRcfdHDOrbi51p9/wf/omi7KthvBA6Q6mOg1YS71nbsT0aofRh+08s6AuWmMEPNRL7PXNXTyG8/tSwI/31LZrMKaJFTnNVxn9m0mWFPuhIZLlvVz8CgND0JAmWAvUja7WGQQ6AA2Drc3zsnMikrOQv0Jou/L70sku52NuyPrHeC7xyS8oREqvdQO/CApD+wHdoFxP3iFQecnNQ17JOw3FotNfQkwwrvgTgdnOJU7sj0iMDRjtLl8DX/B9kMP6vxh46KzLagSt136mCxZl30pU5fFE8pyIcdIrgGTCqeBZhnMpJ6vReOc8rs8WyY4nL1LpFt+rNzDaKQvYYQzpYf7kZyWGSwt+drJWZrmDqkNbivm2Mp97oa8ZMubO9UQ9s7gbEVCxMKsneOqDxSO+YRzf/tH5X9R40o9ZP5J9vA5U9V5OizwpAKvIddq1p5OJGJyqiwKPvOk2zWRVV4dwwDnwM/h+rM/aDP+CGPLye6kjLxEqlU3gfLr5wqZy9iw7vnvTKDOVvceKz5vo2VJ2BsZe2K3eMqXp8R39zLMGEBf1w30WA0iwzh2gabWxYnFp5mEPY/OBybo5c=
  - secure: liBy17BIN6z/bDO6YH+JAo+61bnxYQLIO4Wym8sSW2gZ4kzbDZPAxbuQqNPlrAenpZs36pIt9cgl5fvagyOoR3KjZ32qpTUVQYr7VX+YghrZOIKYvLGZNPnqNYglLLx8Jd9leGf1SreLNJ5ge/bTQoUq4WFUUr/ttV3/T0KdWp8jZZtRjCHzj74NQJgeZiCIfJKl+BdfYKeuhaLJmfo/1LVmDhArd90hcEyEdsL367ylDH3/AfBA5F+80/GtVgeNw2FJhu9I0GAwRb5mDLycqqCbeUVn6wvb17Sbto/tEILlk1qlN0Zr9jnXTDFBA+85zWzvYF1/x+Dd5IeGeBt9Af99wgeWEIKz/G7QD3/lJgNjdFzEF1F/GC9Si+VthzKubhC9hJ76Lgh7QIbFwTQijJ2zvqyZaWU04SDeR3jHQAOVBhQgyMtXROokdv1Utnmq9ZpbjJvP+i8Q2lz9WUD42ga5GeB6sHxaak+h3ke5idHcd0JQimku7+AYFGmdYPt/tIFjwwR8XXDFMGNSSZHqghk9yv0nOeyQZQo73bQYuXPwIw3GxcmfQLOdt6hb7ESNo4xzG8qFdeCl84qzW862uA6X/m8910PqnPig9EKjPMLaHf9JXE15rj+B05yU3qfpnMLLmh9/KQGn83jrEzwI+dMQGEJNbxIDRW6cru/tk9w=
